# Generated by Django 5.2.5 on 2025-11-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developersApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userRegister',
        ),
    ]
