# Generated by Django 5.2.6 on 2025-09-16 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('projects', models.ManyToManyField(blank=True, related_name='developers', to='developersApp.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Developers',
        ),
        migrations.AddField(
            model_name='skill',
            name='developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='developersApp.developer'),
            preserve_default=False,
        ),
    ]
