# Generated by Django 5.2.5 on 2025-12-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developersApp', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('do_Project', 'can do project')]},
        ),
    ]
