# Generated by Django 5.2.5 on 2025-09-18 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developersApp', '0003_alter_skill_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='developer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='developersApp.developer'),
        ),
    ]
