# Generated by Django 5.2.5 on 2025-09-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developersApp', '0004_alter_skill_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(blank=True, related_name='projects', to='developersApp.developer'),
        ),
    ]
