# Generated by Django 5.2.5 on 2025-12-24 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developersApp', '0004_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'permissions': [('can_edit_own_profile', 'can edit own profile'), ('can_edit_own_Prject', 'can edit own Prject')]},
        ),
    ]
